# Generated by Django 5.2.4 on 2026-01-05 15:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import tms.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tms.models.category_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TMS Furnitures', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('phone', models.CharField(default='+91 96298 28969', max_length=15)),
                ('email', models.EmailField(default='info@tmsfurnitures.com', max_length=254)),
                ('address', models.TextField(default="Tamil Nadu's Most Trusted and Premium Brand")),
                ('copyright_text', models.CharField(default='TMS Furniture | All rights reserved', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('short_desc', models.TextField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('regular_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('deal_end_date', models.DateField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=tms.models.product_video_path, validators=[tms.models.validate_video_size])),
                ('in_stock', models.BooleanField(default=True)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_limited_deal', models.BooleanField(default=False)),
                ('is_special_offer', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('call_for_price', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('enquiry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tms.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tms.models.product_image_path)),
                ('is_main', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tms.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='tms.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tms.models.product_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tms.product')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='tms.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=tms.models.store_logo_path)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('working_hours', models.CharField(default='10 AM - 9 PM', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tms.store'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New Enquiry'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('just enquiry', 'Just Enquiry')], default='new', max_length=20)),
                ('source', models.CharField(default='form', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tms.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tms.productvariant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='tms.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tms.store'),
        ),
        migrations.CreateModel(
            name='StoreAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_admins', to='tms.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_desktop', models.ImageField(upload_to=tms.models.banner_desktop_path)),
                ('image_tablet', models.ImageField(blank=True, null=True, upload_to=tms.models.banner_tablet_path)),
                ('image_mobile', models.ImageField(upload_to=tms.models.banner_mobile_path)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='tms.store')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Color, Size, Material, Finish', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='tms.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VariantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.variantattribute')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tms.productvariant')),
            ],
            options={
                'ordering': ['attribute__name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['short_desc'], name='short_desc_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='product_search_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_featured', 'is_best_seller'], name='tms_product_store_i_864489_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'deal_end_date'], name='tms_product_store_i_cb4716_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'created_at'], name='tms_product_store_i_2f7004_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'category'], name='tms_product_store_i_ed7cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'in_stock', 'is_featured'], name='tms_product_store_i_70a1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'created_at', 'is_new_arrival'], name='tms_product_store_i_ed551f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', '-id'], name='idx_created_at_desc_id_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at', 'id'], name='idx_created_at_asc_id_asc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('offer_price__isnull', False)), fields=['-offer_price', '-id'], name='idx_offer_price_desc_id_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('offer_price__isnull', False)), fields=['offer_price', 'id'], name='idx_offer_price_asc_id_asc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('offer_price__isnull', True)), fields=['-regular_price', '-id'], name='idx_regular_price_desc_id_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('offer_price__isnull', True)), fields=['regular_price', 'id'], name='idx_regular_price_asc_id_asc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'offer_price', 'regular_price'], name='idx_store_effective_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', '-created_at', '-id'], name='idx_store_created_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_product_name'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-created_at'], name='tms_lead_created_ecfe52_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'store'], name='tms_lead_status_41fc57_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['product'], name='tms_lead_product_ae65fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['variant'], name='tms_lead_variant_cd5d91_idx'),
        ),
        migrations.AddIndex(
            model_name='storebanner',
            index=models.Index(fields=['store', 'is_active', 'order'], name='tms_storeba_store_i_291a78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together={('product', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='variantvalue',
            unique_together={('variant', 'attribute')},
        ),
    ]
