# Generated by Django 5.2.4 on 2025-11-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(blank=True, default=dict),
        ),
    ]
