# Generated by Django 5.2.4 on 2025-12-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('contacted', 'Contacted'), ('Interested', 'Interested'), ('Just Enquiry', 'Just Enquiry')], default='new', max_length=20),
        ),
    ]
