# Generated by Django 5.2.4 on 2025-12-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='call_for_price',
            field=models.BooleanField(default=False, help_text="Show 'Call for Best Price' instead of price"),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Material, Dimensions, Warranty', max_length=200)),
                ('value', models.CharField(help_text='e.g. Teak Wood, 6x3 feet, 5 Years', max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='tms.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
