# Generated by Django 5.2.4 on 2025-11-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_storebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
