# Generated by Django 5.2.4 on 2026-01-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_alter_product_regular_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead / Enquiry', 'verbose_name_plural': 'Leads / Enquiries'},
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='tms_lead_variant_cd5d91_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='variant',
        ),
        migrations.AddField(
            model_name='lead',
            name='product_display_name',
            field=models.CharField(blank=True, help_text='Combined product name + selected variant (if any)', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='tms_lead_phone_6ff3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at', 'store'], name='tms_lead_created_ada9af_idx'),
        ),
    ]
