# Generated by Django 5.2.4 on 2025-11-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_alter_product_slug_alter_product_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
    ]
