# Generated by Django 5.2.4 on 2025-12-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_product_call_for_price_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='Green badge to show newly arrived'),
        ),
    ]
