# Generated by Django 5.2.4 on 2025-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_remove_product_subcategory_remove_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
