# Generated by Django 5.2.4 on 2025-12-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_product_is_new_arrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TMS Furnitures', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('phone', models.CharField(default='+91 96298 28969', max_length=15)),
                ('email', models.EmailField(default='info@tmsfurnitures.com', max_length=254)),
                ('address', models.TextField(default="Tamil Nadu's Most Trusted Furniture Brand")),
                ('copyright_text', models.CharField(default='TMS | All rights reserved', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='tms.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
