# Generated by Django 5.2.4 on 2025-12-18 06:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import tms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_sitesettings_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='call_for_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='deal_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_limited_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_special_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=tms.models.product_video_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=tms.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='image_desktop',
            field=models.ImageField(upload_to=tms.models.banner_desktop_path),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='image_mobile',
            field=models.ImageField(upload_to=tms.models.banner_mobile_path),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to=tms.models.banner_tablet_path),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['short_desc'], name='short_desc_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='product_search_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store'], name='tms_product_store_i_fda07d_idx'),
        ),
    ]
