# Generated by Django 5.2.4 on 2025-11-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_alter_productimage_options_productimage_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
    ]
