# Generated by Django 5.2.4 on 2025-12-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0006_product_search_vector_alter_product_call_for_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('contacted', 'Contacted'), ('Converted', 'Converted'), ('Just Enquiry', 'Just Enquiry')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default="Tamil Nadu's Most Trusted and Premium Brand"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='TMS Furniture | All rights reserved', max_length=200),
        ),
    ]
