# Generated by Django 5.2.4 on 2025-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0006_remove_lead_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Best Selling Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_limited_deal',
            field=models.BooleanField(default=False, help_text='Limited Deal (Urgency)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_special_offer',
            field=models.BooleanField(default=False, help_text='Special Offer'),
        ),
    ]
