# Generated by Django 5.2.4 on 2025-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0007_product_is_best_seller_product_is_limited_deal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_style',
        ),
        migrations.AlterField(
            model_name='product',
            name='deal_end_date',
            field=models.DateField(blank=True, help_text='Set date → Becomes Deal of the Day', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Auto calculated', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Hide if out of stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='Gold Badge - Highest Priority'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Orange FEATURED Ribbon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_limited_deal',
            field=models.BooleanField(default=False, help_text='Red LIMITED DEAL Badge'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_special_offer',
            field=models.BooleanField(default=False, help_text='Purple SPECIAL OFFER Badge'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Discounted Price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=0, help_text='Original MRP', max_digits=12),
        ),
    ]
